//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Answerid { get; set; }
        public int rosterid { get; set; }
        public int examitemid { get; set; }
        public string answervalue { get; set; }
        public bool isCorrect { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual examitem examitem { get; set; }
        public virtual roster roster { get; set; }
    }
}
