//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseoutcome
    {
        public courseoutcome()
        {
            this.subskillincourseoutcomes = new HashSet<subskillincourseoutcome>();
        }
    
        public int crsoutcomesid { get; set; }
        public Nullable<int> courseid { get; set; }
        public string crsoutcometext { get; set; }
        public string crsshortoutcome { get; set; }
        public Nullable<int> crssequencenum { get; set; }
        public string crsoutcomenum { get; set; }
    
        public virtual course course { get; set; }
        public virtual ICollection<subskillincourseoutcome> subskillincourseoutcomes { get; set; }
    }
}
