//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class curriculum
    {
        public curriculum()
        {
            this.BKLevel1 = new HashSet<BKLevel1>();
            this.BKLevel2 = new HashSet<BKLevel2>();
            this.CurriculumPeoples = new HashSet<CurriculumPeople>();
            this.programs = new HashSet<program>();
            this.sponsors = new HashSet<sponsor>();
        }
    
        public int curriculumid { get; set; }
        public string curriculum_shortname { get; set; }
        public string curriculum_longname { get; set; }
    
        public virtual ICollection<BKLevel1> BKLevel1 { get; set; }
        public virtual ICollection<BKLevel2> BKLevel2 { get; set; }
        public virtual ICollection<CurriculumPeople> CurriculumPeoples { get; set; }
        public virtual ICollection<program> programs { get; set; }
        public virtual ICollection<sponsor> sponsors { get; set; }
    }
}
