//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public exam()
        {
            this.examitems = new HashSet<examitem>();
            this.taker_exam_status = new HashSet<taker_exam_status>();
            this.scheduled_exam = new HashSet<scheduled_exam>();
        }
    
        public int examid { get; set; }
        public Nullable<int> etypeid { get; set; }
        public string examname { get; set; }
        public string exampurpose { get; set; }
        public decimal duration { get; set; }
        public int examstatusid { get; set; }
        public Nullable<int> programid { get; set; }
    
        public virtual etype etype { get; set; }
        public virtual ICollection<examitem> examitems { get; set; }
        public virtual program program { get; set; }
        public virtual ICollection<taker_exam_status> taker_exam_status { get; set; }
        public virtual ICollection<scheduled_exam> scheduled_exam { get; set; }
        public virtual exam_status exam_status { get; set; }
    }
}
