//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class examitem
    {
        public examitem()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int examitemid { get; set; }
        public Nullable<int> examid { get; set; }
        public Nullable<int> key1id { get; set; }
        public Nullable<int> key2id { get; set; }
        public Nullable<int> key3id { get; set; }
        public string questionobjective { get; set; }
        public string stem { get; set; }
        public string destractor1 { get; set; }
        public string destractor2 { get; set; }
        public string destractor3 { get; set; }
        public string destractor4 { get; set; }
        public string correctanswer { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual exam exam { get; set; }
        public virtual key1 key1 { get; set; }
        public virtual key2 key2 { get; set; }
        public virtual key3 key3 { get; set; }
    }
}
