//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExK1
    {
        public ExK1()
        {
            this.etypes = new HashSet<etype>();
            this.key1 = new HashSet<key1>();
        }
    
        public int exk1ID { get; set; }
        public string exk1Value { get; set; }
    
        public virtual ICollection<etype> etypes { get; set; }
        public virtual ICollection<key1> key1 { get; set; }
    }
}
