//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExK2
    {
        public ExK2()
        {
            this.etypes = new HashSet<etype>();
            this.key2 = new HashSet<key2>();
        }
    
        public int exk2ID { get; set; }
        public string exk2Value { get; set; }
    
        public virtual ICollection<etype> etypes { get; set; }
        public virtual ICollection<key2> key2 { get; set; }
    }
}
