//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExK3
    {
        public ExK3()
        {
            this.etypes = new HashSet<etype>();
            this.key3 = new HashSet<key3>();
        }
    
        public int exk3ID { get; set; }
        public string exk3Value { get; set; }
    
        public virtual ICollection<etype> etypes { get; set; }
        public virtual ICollection<key3> key3 { get; set; }
    }
}
