//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class institution
    {
        public institution()
        {
            this.InstitutionPrograms = new HashSet<InstitutionProgram>();
            this.institutionpeoples = new HashSet<institutionpeople>();
            this.svtables = new HashSet<svtable>();
        }
    
        public int institutionid { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string st { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string weburl { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<bool> isaccredited { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createdbywhom { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> modifiedbywhom { get; set; }
    
        public virtual ICollection<InstitutionProgram> InstitutionPrograms { get; set; }
        public virtual ICollection<institutionpeople> institutionpeoples { get; set; }
        public virtual ICollection<svtable> svtables { get; set; }
    }
}
