//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class institutionpeople
    {
        public institutionpeople()
        {
            this.scheduled_exam = new HashSet<scheduled_exam>();
        }
    
        public int institutionpeopleid { get; set; }
        public int personid { get; set; }
        public int institutionid { get; set; }
        public bool isISA { get; set; }
        public bool isProctor { get; set; }
        public bool isReports { get; set; }
    
        public virtual institution institution { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<scheduled_exam> scheduled_exam { get; set; }
    }
}
