//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class key1
    {
        public key1()
        {
            this.examitems = new HashSet<examitem>();
        }
    
        public int key1id { get; set; }
        public Nullable<int> exk1ID { get; set; }
        public int courseid { get; set; }
        public string crsoutcometext { get; set; }
    
        public virtual course course { get; set; }
        public virtual ICollection<examitem> examitems { get; set; }
        public virtual ExK1 ExK1 { get; set; }
    }
}
