//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class key3
    {
        public key3()
        {
            this.examitems = new HashSet<examitem>();
        }
    
        public int key3id { get; set; }
        public Nullable<int> exk3ID { get; set; }
        public int SkillsID { get; set; }
        public string SubskillTitle { get; set; }
    
        public virtual ICollection<examitem> examitems { get; set; }
        public virtual ExK3 ExK3 { get; set; }
        public virtual skill skill { get; set; }
    }
}
