//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class program
    {
        public program()
        {
            this.BKLevel1 = new HashSet<BKLevel1>();
            this.BKLevel2 = new HashSet<BKLevel2>();
            this.courses = new HashSet<course>();
            this.exams = new HashSet<exam>();
            this.InstitutionPrograms = new HashSet<InstitutionProgram>();
            this.programstatushistories = new HashSet<programstatushistory>();
            this.skillclasses = new HashSet<skillclass>();
        }
    
        public int programid { get; set; }
        public string shortname { get; set; }
        public string longname { get; set; }
        public string description { get; set; }
        public Nullable<int> curriculumid { get; set; }
        public Nullable<int> programstatusid { get; set; }
    
        public virtual ICollection<BKLevel1> BKLevel1 { get; set; }
        public virtual ICollection<BKLevel2> BKLevel2 { get; set; }
        public virtual ICollection<course> courses { get; set; }
        public virtual curriculum curriculum { get; set; }
        public virtual ICollection<exam> exams { get; set; }
        public virtual ICollection<InstitutionProgram> InstitutionPrograms { get; set; }
        public virtual ICollection<programstatushistory> programstatushistories { get; set; }
        public virtual programstatu programstatu { get; set; }
        public virtual ICollection<skillclass> skillclasses { get; set; }
    }
}
