//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduled_exam
    {
        public scheduled_exam()
        {
            this.rosters = new HashSet<roster>();
            this.svtables = new HashSet<svtable>();
        }
    
        public int scheduledexamid { get; set; }
        public Nullable<int> institutionpeopleid { get; set; }
        public Nullable<int> examid { get; set; }
        public System.DateTime examstarttime { get; set; }
        public System.DateTime examendtime { get; set; }
        public System.DateTime examdate { get; set; }
        public string examlocation { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual institutionpeople institutionpeople { get; set; }
        public virtual ICollection<roster> rosters { get; set; }
        public virtual ICollection<svtable> svtables { get; set; }
    }
}
