//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public skill()
        {
            this.key3 = new HashSet<key3>();
            this.subskills = new HashSet<subskill>();
        }
    
        public int skillsid { get; set; }
        public Nullable<int> skillsclassid { get; set; }
        public string skillsname { get; set; }
    
        public virtual ICollection<key3> key3 { get; set; }
        public virtual skillclass skillclass { get; set; }
        public virtual ICollection<subskill> subskills { get; set; }
    }
}
