//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subskillincourseoutcome
    {
        public int SubSkillCrsOutID { get; set; }
        public Nullable<int> SubSkillID { get; set; }
        public Nullable<int> CourseOutcomesID { get; set; }
    
        public virtual courseoutcome courseoutcome { get; set; }
    }
}
