//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taker_exam_status
    {
        public int taker_exam_statusid { get; set; }
        public Nullable<int> examid { get; set; }
        public Nullable<int> takerid { get; set; }
        public string oldstatus { get; set; }
        public string newstatus { get; set; }
        public System.DateTime modifieddate { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual taker taker { get; set; }
    }
}
