//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taker
    {
        public taker()
        {
            this.rosters = new HashSet<roster>();
            this.svtables = new HashSet<svtable>();
            this.taker_exam_status = new HashSet<taker_exam_status>();
        }
    
        public int takerid { get; set; }
        public int personid { get; set; }
        public string program { get; set; }
        public string graduationyear { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<roster> rosters { get; set; }
        public virtual ICollection<svtable> svtables { get; set; }
        public virtual ICollection<taker_exam_status> taker_exam_status { get; set; }
    }
}
